config/routes.rb
Rails.application.routes.draw do
  get 'quotes/index'
  get 'quotes/new'
  # go to this page if url is not found
  get '*path' => redirect('/')
  get 'quotes/*path' => redirect('/')

  resources :quotes
  #set up landing page 
  root to: 'quotes#index'
   
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  # show all quotes
   def index
        @quote = Quote.all.paginate(:page => params[:page], :per_page => 12).order("created_at DESC")
    end  
    
  # render new quote form
    def new
        @quote = Quote.new
    end
  # saves new quote in db
    def create
     @quote = Quote.new(quote_params)
     if @quote.save
          redirect_to quotes_path
     else 
          render ‘new’
     end 
    end
    def quote_params
        params.require(:quote).permit(:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Iquotes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quotes/index.html.erb
<div class ="box border">
	<div id="head" class="border">
		<h1>Welcome to iQuote</h1>
		<h2> Best movie quotes you can find</h2>
		<strong><%= link_to 'Add new quote', new_quote_path %></strong>
	</div>
	<div>
		<% @quote.each do |quote| %>
		    <h3>"<%= quote.body%>"</h3>
		    <p><%= quote.created_at.strftime('Created on %d %B %Y') %></p>
		    <hr>
		<% end %>
		<%= will_paginate @quote %>
	</div>
</div>

app/views/quotes/new.html.erb
<div class="box" id="form">
	<h1>Add new quote</h1>
	<h5>It better be a good one</h5>
	<%= form_for (@quote) do |f| %>
	    <p>
	        <%= f.text_area :body %><br />
	    </p>
	    <p>
	        <%= f.submit "Submit" %>
	    </p>
	<% end %>
</div>